language: php

php:
   - 5.6
   - 7.2

services:
   - memcached

env:
   - COMPOSER_MEMORY_LIMIT=-1

before_script:
   - composer install --no-interaction

script:
   - vendor/bin/phpunit -c phpunit.xml.dist --coverage-text
